name: fix-code-style

on:
  push:

# Добавьте этот блок
permissions:
  contents: write
  workflows: write

jobs:
  fix-code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Важно использовать токен с новыми правами
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: Set up Node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: |
          composer install --no-interaction
          npm ci
      - name: Run Pint
        run: composer pint
      - name: Run Prettier
        run: npm run prettier
      - name: Pull changes
        run: git pull
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: >
            chore: fix code style
